services:
  catalogue:
    build: ./catalogue # it move to catalogue directory 
    image: surendra3207/catalogue:1.0.0 # it will build the image like docker build -t surendra3207/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    build: ./user
    image: surendra3207/user:1.0.0
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    build: ./cart
    image: surendra3207/cart:1.0.0
    container_name: cart
    depends_on:
    - redis
    - catalogue
  shipping:
    build: ./shipping
    image: surendra3207/shipping:1.0.0
    container_name: shipping
    depends_on:
    - mysql
  frontend:
    build: ./frontend
    image: surendra3207/frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
  mongodb:
    build: ./mongodb
    image: surendra3207/mongodb:1.0.0
    container_name: mongodb
  redis:
    build: ./redis
    image: surendra3207/redis:1.0.0
    container_name: redis
  mysql:
    build: ./mysql
    image: surendra3207/mysql:1.0.0
    container_name: mysql
  rabbitmq:
    build: ./rabbitmq
    image: surendra3207/rabbitmq:1.0.0
    container_name: rabbitmq

networks:
  default:
    driver: bridge
    name: roboshop
    external: false #if true you need to create network manually 